### ISSUE TITLE
Failed to resolve component 'jsmn'

### ISSUE THREAD

**Issue by MPSMPS** [jorgenkraghjakobsen/snapclient#40]
Hi,

I am trying to start with this project. I installed everything so far as I am aware of it. But during idf.py menuconfig I get the error: Failed to resolve component 'jsmn'

I found it in ./esp-adf/esp-idf/components/jsmn but idf.py menuconfig does not find it. Any suggestions what might be wrong? As far as I understand the components are registered in the CMakeFiles.txt from the esp-adf.

I am quite new to esp-idf / esp-adf. Any hints I should looking for?

Thanks!
Regards
Mathias

**Comment by darkguinito** [comment]
Hello,

As you, I'm just starting with this project and more globally a complet noob with ESP32.
I think I had success to bypass your problem.
Here is command I made to be able to build this project on an linux arch system.

```bash
git clone https://github.com/jorgenkraghjakobsen/snapclient.git
cd snapclient/
git submodule update --init

# Add managed components
cat >main/idf_component.yml <<EOF
## IDF Component Manager Manifest File
dependencies:
  espressif/nghttp: "*"
  espressif/jsmn: "*"
  ## Required IDF version
  idf:
    version: ">=4.1.0"
EOF

# ESP-IDF install & setup
mkdir ~/esp
cd ~/esp
git clone --recursive https://github.com/espressif/esp-idf.git
cd ~/esp/esp-idf
./install.sh esp32
. ./export.sh

# ESP-ADF install & setup
git clone --recursive https://github.com/espressif/esp-adf.git
export ADF_PATH=~/esp/esp-adf
. $HOME/esp/esp-idf/export.sh
cd -
idf.py set-target esp32
idf.py reconfigure 
idf.py -p /dev/ttyUSB0 flash
idf.py -p /dev/ttyUSB0 monitor
```

Hope it helps, and if anyone had success to use this snapclient version on raspiaudio board (#27), i am highly interested :)

**Comment by MPSMPS** [comment]
Hi,

thanks for your help. It was simply the missing idf_component.yml. Rest of my setup was right.
