### ISSUE TITLE
esp32-s3 & ntp

### ISSUE THREAD

**Issue by StuartIanNaylor** [jorgenkraghjakobsen/snapclient#44]
Would the newer esp32-s3 provide a better platform for a esp32-snapclient?

Also is it true NTP & SNTP from the IDF have really big tolerances that could cause large buffer requirements and is https://github.com/gmag11/ESPNtpClient [High accuracy NTP library for ESP32 and ESP8266] worth it to reduce buffer requirements?

**Comment by CarlosDerSeher** [comment]
Snapclient doesn't use (S)NTP. Time since boot is used for timestamps in Server and client.
